repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [ '--unsafe' ] # checks syntax without loading yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    # Getting mypy to work in pre-commit have always been tricky
    # pre-commit/mirrors-mypy isn't good enough since its env and config
    # could differ with local environment, leading to unexpected behavior.
    # Here we use the mypy installed in local env instead
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [ python ]
        require_serial: true
        verbose: true
